version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Compile
          command: make game
      - run:
          name: Unit tests
          command: make test
